name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  build:
    name: Build PlatformPlatform documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Node modules
        run: bun install --frozen-lockfile

      - name: Build static pages
        run: bun build

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "doc_build/"

  deploy:
    name: Deploy PlatformPlatform documentation
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
